export const CONDITIONS = [
  { key: "diabetes",     label: "Diabetes",       icon: "🩸" },
  { key: "hypertension", label: "Hypertension",   icon: "💓" },
  { key: "depression",   label: "Depression",     icon: "🧠" },
  { key: "cvd",          label: "Cardiovascular", icon: "❤️" },
  { key: "fatty_liver",  label: "Fatty Liver",    icon: "🫁" },
];

export const FEATURE_LABELS = {
    age:                            "Age",
    sex_male:                       "Sex",
    gender:                         "Gender",
    bmi:                            "BMI",
    weight_kg:                      "Weight",
    height_cm:                      "Height",
    waist_cm:                       "Waist Circumference",
    general_health_self_report:     "General Health",
    sleep_hours_weekday:            "Sleep Duration",
    sedentary_minutes_per_day:      "Sedentary Time",
    any_tobacco_use:                "Tobacco Use",
    smoked_100_cigarettes_lifetime: "Smoked 100+ Cigarettes (lifetime)",
    current_smoker:                 "Current Smoker",
    binge_drinking_past_year:       "Binge Drinking (past year)",
    has_health_insurance:           "Health Insurance",
    routine_care_place:             "Regular Care Place",
    tried_to_lose_weight_past_year: "Tried to Lose Weight (past year)",
    adult_food_security:            "Food Security",
    day1_calories:                  "Calories (typical day)",
    day1_protein_g:                 "Protein (typical day)",
    day1_total_sugar_g:             "Sugar (typical day)",
    day1_caffeine_mg:               "Caffeine (typical day)",
    phq_little_interest:            "Little Interest or Pleasure",
    phq_feeling_down:               "Feeling Down or Hopeless",
    phq_sleep_problems:             "Sleep Problems",
    phq_tired:                      "Fatigue / Low Energy",
    phq_poor_appetite:              "Poor Appetite",
    phq_feeling_bad_about_self:     "Feeling Bad About Self",
    phq_trouble_concentrating:      "Trouble Concentrating",
    phq_moving_slowly:              "Moving or Speaking Slowly",
    phq_thoughts_of_harm:           "Thoughts of Self-Harm",
    short_sleep:                    "Short Sleep (<6h)",
    long_sleep:                     "Long Sleep (>9h)",
    // lab values shown in SHAP but not user inputs
    total_cholesterol_mgdl:         "Total Cholesterol",
    hdl_cholesterol_mgdl:           "HDL Cholesterol",
    ldl_cholesterol_mgdl:           "LDL Cholesterol",
    triglycerides_mgdl:             "Triglycerides",
    hba1c_pct:                      "HbA1c",
    fasting_glucose_mgdl:           "Fasting Glucose",
    crp_inflammation_mgl:           "CRP (Inflammation)",
    alt_liver_enzyme_ul:            "ALT (Liver Enzyme)",
    ast_liver_enzyme_ul:            "AST (Liver Enzyme)",
    ggt_liver_enzyme_ul:            "GGT (Liver Enzyme)",
    uric_acid_mgdl:                 "Uric Acid",
    hemoglobin_gdl:                 "Hemoglobin",
    white_blood_cells:              "White Blood Cells",
    platelets:                      "Platelets",
    medication_count:               "Medication Count",
    income_poverty_ratio:           "Income/Poverty Ratio",
    race_ethnicity:                 "Race/Ethnicity",
    education:                      "Education Level",
    occupation_category:            "Occupation",
    snap_benefits:                  "SNAP Benefits",
    healthcare_visits_past_year:    "Healthcare Visits (past year)",
    high_cholesterol_diagnosis:     "High Cholesterol Diagnosis",
    prediabetes_diagnosis:          "Prediabetes",
    albumin_creatinine_ratio:       "Albumin/Creatinine Ratio",
    congestive_heart_failure:       "Congestive Heart Failure",
    self_reported_weight_1yr_ago:   "Weight 1 Year Ago",
    liver_condition:                "Liver Condition",
    tried_to_lose_weight_past_year: "Tried to Lose Weight",
    hours_worked_per_week:          "Hours Worked per Week",
    arm_circumference_cm:           "Arm Circumference",
    born_in_us:                     "Born in US",
    general_health_self_report:     "General Health",
    urine_albumin_ugml:             "Urine Albumin",
    urine_creatinine_mgdl:          "Urine Creatinine",
    ferritin_ngml:                  "Ferritin",
    insulin_uuml:                   "Insulin",
    taking_insulin:                 "Taking Insulin",
    wake_time:                      "Wake Time",
    sleep_time:                     "Sleep Time",
    hours_fasted_before_exam:       "Hours Fasted Before Exam",
    glucose_serum_mgdl:             "Serum Glucose",
    red_cell_distribution_width:    "Red Cell Distribution Width",
    hematocrit_pct:                 "Hematocrit",
    total_bilirubin_mgdl:           "Total Bilirubin",
    total_protein_gdl:              "Total Protein",
    albumin_gdl:                    "Albumin",
    creatinine_mgdl:                "Creatinine",
    self_reported_height_inches:    "Self-Reported Height",
    self_reported_weight_lbs:       "Self-Reported Weight",
    cancer_diagnosis:               "Cancer Diagnosis",
    asthma_diagnosis:               "Asthma Diagnosis",
    anemia_diagnosis:               "Anemia Diagnosis",
    kidney_disease:                 "Kidney Disease",
    stroke:                         "Stroke",
    heart_attack:                   "Heart Attack",
    angina:                         "Angina",
    adult_food_security:            "Food Security",
    routine_care_place:             "Regular Care Place",
    has_health_insurance:           "Health Insurance",
    household_size:                 "Household Size",
    served_in_military:             "Served in Military",
    ecigarette_use:                 "E-Cigarette Use",
    smoked_100_cigarettes_lifetime: "Smoked 100+ Cigarettes",
    current_smoker:                 "Current Smoker",
    binge_drinking_past_year:       "Binge Drinking",
    avg_drinks_per_day:             "Avg Drinks per Day",
};

export const SELECTED_FEATURES = [
    "age",
    "sex_male",
    "bmi",
    "weight_kg",
    "height_cm",
    "waist_cm",
    "general_health_self_report",
    "sleep_hours_weekday",
    "sedentary_minutes_per_day",
    "any_tobacco_use",
    "smoked_100_cigarettes_lifetime",
    "current_smoker",
    "binge_drinking_past_year",
    "has_health_insurance",
    "routine_care_place",
    "tried_to_lose_weight_past_year",
    "adult_food_security",
    "day1_calories",
    "day1_protein_g",
    "day1_total_sugar_g",
    "day1_caffeine_mg",
    "phq_little_interest",
    "phq_feeling_down",
    "phq_sleep_problems",
    "phq_tired",
    "phq_poor_appetite",
    "phq_feeling_bad_about_self",
    "phq_trouble_concentrating",
    "phq_moving_slowly",
    "phq_thoughts_of_harm",
];

export const DEFAULT_FEATURES = {
    age:                            45,
    gender:                         "Male",
    bmi:                            26.0,
    weight_kg:                      70,
    height_cm:                      170,
    waist_cm:                       88,
    general_health_self_report:     "Good",
    sleep_hours_weekday:            7.0,
    short_sleep:                    0,
    long_sleep:                     0,
    sedentary_minutes_per_day:      360,
    any_tobacco_use:                0,
    smoked_100_cigarettes_lifetime: "No",
    current_smoker:                 "Not at all",
    binge_drinking_past_year:       "No",
    has_health_insurance:           "Yes",
    routine_care_place:             "Yes",
    tried_to_lose_weight_past_year: "No",
    adult_food_security:            "Full security",
    day1_calories:                  2000,
    day1_protein_g:                 80,
    day1_total_sugar_g:             50,
    day1_caffeine_mg:               100,
    phq_little_interest:            0,
    phq_feeling_down:               0,
    phq_sleep_problems:             0,
    phq_tired:                      0,
    phq_poor_appetite:              0,
    phq_feeling_bad_about_self:     0,
    phq_trouble_concentrating:      0,
    phq_moving_slowly:              0,
    phq_thoughts_of_harm:           0,
};

export function getRiskLevel(score) {
    if (score < 25) return "low";
    if (score < 55) return "moderate";
    return "high";
}

export function getRiskLabel(score) {
    if (score < 25) return "Low";
    if (score < 55) return "Moderate";
    return "High";
}

export const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || "http://127.0.0.1:8000";
